### ISSUE TITLE
Skill issue 

### ISSUE THREAD

**Issue by Mark-74** [Pit17/Lezioni4H#1]
# Skill Issue
## Skill
- issue
- issue
- issue

**Comment by AlBovo** [comment]
cosa mi copi le idee di issues

**Comment by AlBovo** [comment]
mi elimini i commenti?

**Comment by AlBovo** [comment]
mi elimini i commenti?

**Comment by AlBovo** [comment]
mi elimini i commenti?

**Comment by AlBovo** [comment]
mi elimini i commenti?
